apiVersion: v1
kind: Service
metadata:
  name: external-rest
spec:
  ports:
  - name: firewalld
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-rest
subsets:
  -
    addresses:
      -
        ip: 10.87.103.96 #private IP of server
    ports:
      -
        port: 8080
        name: firewalld